PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_CLIENTES'
  MODULE TC_CLIENTES_INIT.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_COL_ATTR.
  LOOP AT   G_TC_CLIENTES_ITAB
       INTO G_TC_CLIENTES_WA
       WITH CONTROL TC_CLIENTES
       CURSOR TC_CLIENTES-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_CLIENTES_CHANGE_FIELD_ATTR
    MODULE TC_CLIENTES_MOVE.
  ENDLOOP.

  MODULE alimenta_tc.
  MODULE STATUS_9000.
  MODULE VALIDA_DADOS_9000.
  MODULE CONTROLE_TELA_9000.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_CLIENTES'
  LOOP AT G_TC_CLIENTES_ITAB.
    CHAIN.
      FIELD Z944620CLI_AUTO-CLIENTE_ID.
      FIELD Z944620CLI_AUTO-NOME_CLIENTE.
      FIELD Z944620CLI_AUTO-CPF_CNPJ.
      FIELD Z944620CLI_AUTO-TIPO_CLIENTE.
      FIELD Z944620CLI_AUTO-EMAIL.
      FIELD Z944620CLI_AUTO-TELEFONE.
      FIELD Z944620CLI_AUTO-MARCA_PREFERIDA.
      FIELD Z944620CLI_AUTO-MODELO_INTERESSE.
      FIELD Z944620CLI_AUTO-DATA_CADASTRO.
      FIELD Z944620CLI_AUTO-ATIVO.
    ENDCHAIN.
  ENDLOOP.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_CLIENTES_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_9000_EXIT AT EXIT-COMMAND.
  MODULE USER_COMMAND_9000.
